# Generated by Django 5.1.2 on 2024-10-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="description",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
    ]
