# Generated by Django 5.1.2 on 2024-10-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_play_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(to="theatre.actor"),
        ),
        migrations.AddField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(to="theatre.genre"),
        ),
    ]
