# Generated by Django 5.1.2 on 2024-10-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0005_alter_play_actors_alter_play_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(null=True, upload_to="???"),
        ),
    ]
