# Generated by Django 5.1.2 on 2024-10-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0007_alter_play_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
    ]
